services:
  extract:
    build: ./file_to_text
    container_name: team21-extract
    ports:
      - "8002:8002"
    restart: unless-stopped
    volumes:
      - ./file_to_text:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]


